### ISSUE TITLE
Unable to get address of deployed contract

### ISSUE THREAD

**Issue by madvas** [MetaMask/metamask-plugin#592]
I am able to deploy contract in console in Mist Browser, whereas the same code doesn't work in Chrome with MetaMask.

This is code I ran in Mist console, you can see I successfully got back new contract's address

![screen shot 2016-08-28 at 09 39 28](https://cloud.githubusercontent.com/assets/3857155/18032411/4b9d8a06-6d04-11e6-940d-3573b3ed2c6a.png)

executed code:
```javascript
var source = "contract test { function multiply(uint a) returns(uint d) { return a * 7; } }"

web3.eth.compile.solidity(source, (err, res) => compiledSrc = res)

compiledSrc

web3.eth.contract(JSON.parse(compiledSrc.test.interface)).new({data: compiledSrc.test.bytecode, gas: 300000, from: web3.eth.accounts[0]}, (err, res) => {console.log(err, res); newContract = res})

newContract.address
```

This is code I ran in Chrome, you can see callback is not called second time, therefore contract's address is never assigned. Note, code is slightly different because `web3.eth.compile.solidity` returns object in different format. But that shouldn't matter for this bug.

<img width="1201" alt="screen shot 2016-08-28 at 09 41 50" src="https://cloud.githubusercontent.com/assets/3857155/18032432/e21331fc-6d04-11e6-8ddc-3f79e2136999.png">

executed code:
```javascript
var source = "contract test { function multiply(uint a) returns(uint d) { return a * 7; } }"

web3.eth.compile.solidity(source, (err, res) => compiledSrc = res)

compiledSrc

web3.eth.contract(compiledSrc.test.info.abiDefinition).new({data: compiledSrc.test.code, gas: 300000, from: web3.eth.accounts[0]}, (err, res) => {console.log(err, res); newContract = res})

newContract.address
```

Using: 
MetaMask 2.9.2
Mist 0.8.2
Geth Version: 1.4.11-stable-fed692f6
network: testnet or private net

**Comment by kumavis** [comment]
@madvas can you try again on `MetaMask 2.10.0`. we just pushed some changes to event handling.

**Comment by kumavis** [comment]
also for 'testnet' - are you using testrpc or morden ?

**Comment by madvas** [comment]
Updated to MetaMask `2.10.0`. Still the same, doesn't work. I'm using Morden. 

Chrome Version 52.0.2743.116 (64-bit)
OSX

**Comment by kumavis** [comment]
@madvas thanks
