### ISSUE TITLE
Invalid Params at Object.Invalid response on code that was working before update

### ISSUE THREAD

**Issue by stuffyvater** [MetaMask/metamask-plugin#679]
Hi I'm working with a prototype with a friend and we had a working prototype 3 days ago before 2.13 but are now both getting this error message when launching our contract: 

Error Message: 
![errormm1](https://cloud.githubusercontent.com/assets/11940919/18678201/8de0eeb2-7f5b-11e6-8f69-a6f218b9d5a5.png)

Code that worked 3 days ago 
![errormm2](https://cloud.githubusercontent.com/assets/11940919/18678202/8de135a2-7f5b-11e6-93b1-389928014d19.png)

l:31 :   $('#yay').html("Yay. Hash is: "+r.transactionHash);

did something change with the update? Thanks in advance!

**Comment by flyswatter** [comment]
Hi! Thanks for the report!

The change that this is almost definitely related to was an update to provider engine that made it compatible with the Parity client, in response to Monday's geth bug.

What I really need to see here is what Params are now being sent and treated as invalid. You could send me your code to try with, or you could inspect it yourself.

To inspect an invalid request sent from metamask, you need to open its background console, set the debugger to pause on uncaught error, and then either step up the stack to inspect the params, or try to find the most recently resolved network request, and post those params here.

I'm not really sure what params would be treated as invalid, our biggest change is actually to incoming data, not outgoing, but that looks like the place to look.

**Comment by stuffyvater** [comment]
Hi thanks for the swift reply and this amazing plugin - No secrets here, this is for a master thesis :-) Here's the code. As indicated in screenshot 2 from my first post the problem starts here
l:31 : `$('#yay').html("Yay. Hash is: "+r.transactionHash);`

full code: 
`<html>
  <head>
  </head>
    <script type="application/javascript" src="./bower_components/jquery/dist/jquery.min.js"></script>
    <script src="https://npmcdn.com/ipfs-api/dist/index.js"></script>
  <body>
    <h2>Create a Contract!</h2>
    <button id="create">Create!</button>
    <div id="yay"></div>
    <br/>
    <hr>
    <h2>Whitelist a Stakeholder</h2>
    Contract Address: <input type="text" id="contractAddress"/><br/>
    Stakeholder ID: <input type="text" id="stakeholderId"/>
    <button id="submit">Go!</button>
    <div id="yay2"></div>
    <hr>
    <h2>Upload/Amend Document</h2>
    Contract Address: <input type="text" id="contractAddress1"/><br/>
    File: <input type="file" id="file"/>
    <button id="submit1">Go!</button>
  <script type="text/javascript">
    $(document).ready(function() {
      var abi = [{"constant":false,"inputs":[{"name":"stakeholder","type":"address"}],"name":"whitelistStakeholder","outputs":[],"type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"whiteList","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":false,"inputs":[{"name":"documentId","type":"uint256"},{"name":"newFingerprint","type":"string"}],"name":"amendDocument","outputs":[],"type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"documents","outputs":[{"name":"author","type":"address"},{"name":"fingerprint","type":"string"}],"type":"function"},{"constant":true,"inputs":[],"name":"admin","outputs":[{"name":"","type":"address"}],"type":"function"},{"inputs":[],"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"stakeholder","type":"address"}],"name":"StakeholderWhitelisted","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"documentId","type":"uint256"},{"indexed":false,"name":"author","type":"address"},{"indexed":false,"name":"newFingerprint","type":"string"}],"name":"DocumentAmended","type":"event"}];
      /* VARIABLES */
      var MyContract = web3.eth.contract(abi);
      $('#create').click(function() {
        var c = MyContract.new({from: web3.eth.coinbase, gas: 300000}, function(e,r) {
          console.log(e);
          console.log(r);
          $('#yay').html("Yay. Hash is: "+r.transactionHash);
        });
      })

      $('#submit').click(function() {
        var contractAddress = $('#contractAddress').val();
        var stakeholder = $('#stakeholderId').val();
        var myContractInstance = MyContract.at(contractAddress);
        console.log(myContractInstance);
        console.log(contractAddress);
        myContractInstance.whitelistStakeholder(stakeholder, {from: web3.eth.coinbase, gas: 91000}, function(e,r) {
          console.log(e);
          console.log(r);
          if (!e) {
            $('#yay2').html('Stakeholder whitelisted');
          }
        });
      });

      $('#submit1').click(function() {
        var files = document.getElementById('file').files;
        if (!files.length) {
            alert('Please select a file!');
            return;
        }

        var file = files[0];
        var reader = new FileReader();

        reader.readAsText(file);
        // If we use onloadend, we need to check the readyState.
        reader.onloadend = function(evt) {
            var i = IpfsApi("/ip4/127.0.0.1/tcp/5001");
            i.add(i.Buffer(reader.result), function (err, res){
                if(err || !res)
                  return console.error("ipfs add error", err, res);

                var storedDoc = res[0];
                var fingerprint = storedDoc.hash;

                $("#hashResult").show();
                $("#hashResult").html(fingerprint);
                console.log("fingerprint: "+ fingerprint);
                contract = web3.eth.contract(abi);

                var contractAddress = $("#contractAddress1").val();
                evt.preventDefault();
                var contractInstance = contract.at(contractAddress);

                contractInstance.amendDocument(1234, fingerprint, {from: web3.eth.coinbase, gas: 1000000}, function(e,r){
                  if(e){
                      alert("An error occurred: " + e);
                  }
                  else {
                      if(r){
                          console.log("The document has been uploaded (fingerprint: " + fingerprint + ")");
                      }
                      console.log(r);
                  }
                });
            });
        };
      })
    });
  </script>
  </body>
</html>
`

**Comment by Miista** [comment]
Dev at the project mentioned in this isssue checking in.
The relevant lines are these:


```javascript
var c = MyContract.new({from: web3.eth.coinbase, gas: 300000}, function(e,r) {
    console.log(e);
    console.log(r);
    $('#yay').html("Yay. Hash is: "+r.transactionHash);
});
```

**Comment by flyswatter** [comment]
Sorry for the slow extra reply, Devcon just finished, and we've been very busy!

This project isn't quite complete enough to reproduce for me: You reference local bower scripts, etc. Ideally you'd give me a link to a github repository, with the `bower.json` committed to it.

That said, a quick skim of your code and it looks to me like you're trying to create a new contract with only an ABI, but no compiled code or current address. This isn't enough to deploy a contract.

Is it possible you removed a critical line, like `var myContractInstance = MyContract.at('0x78e97bcc5b5dd9ed228fed7a4887c0d7287344a9');` or maybe one where you pass the compiled contract bytecode into the constructor to deploy a new one?

**Comment by Miista** [comment]
@flyswatter Here is the link: https://github.com/stuffyvater/M-rskG2/tree/demo

The file in question is this: https://github.com/stuffyvater/M-rskG2/blob/demo/mm1.html
The code for the contract deployment starts at line 29.

> That said, a quick skim of your code and it looks to me like you're trying to create a new contract with only an ABI, but no compiled code or current address. This isn't enough to deploy a contract.

What we have here, is what we had working only 4-5 days ago.

**Comment by Miista** [comment]
Follow-up: compiling using [the online Solidity Compilter](https://ethereum.github.io/browser-solidity/#version=soljson-v0.4.2+commit.af6afb04.js), and copy-pasting the code under **Web3 deploy** doesn't work either.

**Comment by flyswatter** [comment]
Ok, thanks for posting the project.  I’ll try with MetaMask current and a week ago now.

- Dan

**Comment by flyswatter** [comment]
Ok, I successfully pulled your project, installed its dependencies, and deployed your contract!  You can see it here:
https://etherscan.io/tx/0xe629cff23e1f91e02ae4a86704d3c544e98f8f9cdf93d227c4effbc848e47f19

Sorry my earlier thinking was misled, you weren't linking to an old contract, but deploying a new one.

That said, as you can see here, the input data is `0x0`, because you're not adding an application binary, (in the `data` field), just the ABI to the contract.

So we have two problems:

1. Whatever is preventing yours from returning a tx hash (since mine is).
2. How deploying a contract with no binary data ever worked for you.

For the first, could you confirm to me the version of MetaMask you're using? It's visible under `help` in the top right menu.  Maybe also let me know your OS and browser version.

For the second, I recommend reviewing  a doc on [creating and deploying a contract](https://ethereum.gitbooks.io/frontier-guide/content/creating_contract.html).

**Comment by flyswatter** [comment]
Oh, I've replicated by reinstalling metamask locally for some reason.  I'll investigate more, don't bother with more reproduction steps.  Might be after dinner/tomorrow though.

**Comment by flyswatter** [comment]
Could you post me an etherscan link to one of the successful contract deploys?

**Comment by flyswatter** [comment]
I have run through the whole stack, and I am pretty convinced the problem is this line:
```
        var c = MyContract.new(web3.eth.coinbase, {from: web3.eth.coinbase, gas: 300000}, function(e,r) {
```

This is different than the one on your git repository, which might help explain why it worked before and didn't now.

In the git version that I show here, the first argument is the sending account, but that would just get passed to the constructor of the contract, of which there isn't really any, since there's no `data` parameter here.

By the time this gets to our gas-estimating code, web3 has interpreted this request as these RPC parameters:

```
- data : "undefined000000000000000000000000fdea65c8e26263f6d9a1b5de9555d2931a33b825"
-  from : "0xfdea65c8e26263f6d9a1b5de9555d2931a33b825"
-  gas : "0x493e0" 
```

This `data` field is messed up for some weird reasons, I still haven't gotten to the total bottom of it, but the fact that my test-net account is the only coherent bytes in the series is what got me to re-check the code and realize that the account was being passed to the constructor as the first argument.

This has confused our `provider-engine`, which tries to estimate gas on all new transactions, but this one was oddly formed.

We could fix this on our end by identifying badly formed calls to a contract constructor, or generating a more descriptive error here.

If you still think this truly is a metamask update that broke your project, and this code really somehow worked previously, by all means, find the version that could process it [on our releases page](https://github.com/MetaMask/metamask-plugin/releases).

In the meanwhile, I'll treat this issue as a bad error issue, since it's up to us to indicate failure reasons better.

**Comment by Miista** [comment]
@flyswatter I tried adding the `data` field to the request. I have just pushed the code to the repository (on branch `metamask-bug`).
The value for the `data` parameter is taken from the [online Solidity compiler](https://ethereum.github.io/browser-solidity/#version=soljson-v0.4.2+commit.af6afb04.js).
This, still, didn't work.

I even tried compiling the contract code online, and using *only* the code in the *Web deploy* box to try a minimal example.
[Here](https://github.com/stuffyvater/M-rskG2/blob/metamask-bug/metamask-test.html) is a minimal working example, containing no local dependencies.
No dice, unfortunately.


I believe this is a successfully deployed contract: https://testnet.etherscan.io/tx/0xc4287846ccec73085b9455b73180c243823beb50d1e4e9f0b03104cc6d432a48

**Comment by flyswatter** [comment]
Ok it looks like this is related to how we switched a lot of our backend to Parity, to respond to Monday's geth hack.

Turns out there are a couple things to adopt Parity compatibility outstanding, we're patching them in Provider-engine now.

This should be resolved once we bump provider-engine, I'll keep you informed.

**Comment by flyswatter** [comment]
Hey @stuffyvater and @Miista, we finally got to some half decent internet. We fixed what we believe to be the problem bug, could you please verify with the current build, should have updated automatically (`2.13.1`).

**Comment by stuffyvater** [comment]
Hi Dan, thanks for all your help. I am still getting the original error where MM cannot interact with transactionHash. Will ping Miista and see how it works for him

**Comment by flyswatter** [comment]
Ok, well we're beginning a company retreat this week, so apologies in advance that post-Devcon is about to be our least responsive for the year.

We'll try again soon, probably Monday.

- Dan

**Comment by stuffyvater** [comment]
Well deserved rest !:) thank you. Will let you know if something changes

**Comment by stuffyvater** [comment]
Well deserved rest !:) thank you. Will let you know if something changes.  We are showcasing the prototype October 10th so hopefully we'll find something out by then

**Comment by flyswatter** [comment]
Good to know your time constraints, I think we'll easily have you running by then.

Thanks!

- Dan

**Comment by Miista** [comment]
@flyswatter I am still getting the same error.

Using the MWE, mention earlier and found [here](https://github.com/stuffyvater/M-rskG2/blob/metamask-bug/metamask-test.html), I still receive an error, and Metamask doesn't show a popup.

**Comment by stuffyvater** [comment]
Hi Dan are there any news yet? :)

**Comment by stuffyvater** [comment]
Hi Dan, sorry for the impatience, but are there any news yet? :)

**Comment by flyswatter** [comment]
Sorry, we've actually been very busy at our company retreat, not just resting, and also have very spotty internet. If I get a chance, I'll try soon, but the truly guaranteed time will be after this coming weekend.

- Dan

**Comment by stuffyvater** [comment]
Ok thank you Dan! Wouldn't doubt your hard work, just planning for a backup. Let me know if there is anything you want us/me to try. If we still have problems by the 6th of October I think we will try and rebuild completely.

**Comment by flyswatter** [comment]
I won't let you hang that long, I promise, but I might need until after this weekend, because I'll be in continuous transit, usually in flight. May try to fix from a plane.

- Dan

**Comment by stuffyvater** [comment]
Thank you Dan! You guys rock!

**Comment by flyswatter** [comment]
Hi guys, I'm on the case again.

Could I get a quick clarification (we have a lot of instances of the problem floating around):

On your repository at `git@github.com:stuffyvater/M-rskG2.git` you have two related branches: `metamask-bug` and `metamask-test`.

On the branch `metamask-bug` you have two files, `metamask-test.html` and `mm1.html`.

Can we unify on which file is the reproduction case we're testing against?

I'm definitely reproducing some bugs, but since you said it worked before DevCon, I'm trying to make sure I don't go "fixing your code", but instead find what we're doing differently.

**Comment by flyswatter** [comment]
Ok two problems I've noticed, they both seem to be related to Infura (our backend) switching to Parity.

1. Metamask was still adding some parameters to the `estimateGas` call (somehow we missed a couple), and Parity is very picky about data in requests.
2. Parity seems to have some issue where it throws `Invalid Params` in response to gas estimating your contract creation.  The request looks like this:

```
{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from":"0xfdea65c8e26263f6d9a1b5de9555d2931a33b825","data":"606060405260405160208061062e833981016040528080519060200190919050505b80600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908302179055505b506105d28061005c6000396000f360606040526000357c01000000000000000000000000000000000000000000000000000000009004806326ea4bf614610068578063372c12b11461008557806355389c3e146100b8578063c2ed2b051461011c578063f851a440146101ec57610063565b610002565b3461000257610083600480803590602001909190505061022a565b005b34610002576100a0600480803590602001909190505061031d565b60405180821515815260200191505060405180910390f35b346100025761011a6004808035906020019091908035906020019082018035906020019191908080601f016020809104026020016040519081016040528093929190818152602001838380828437820191505050505050909091905050610342565b005b34610002576101376004808035906020019091905050610563565b604051808373ffffffffffffffffffffffffffffffffffffffff168152602001806020018281038252838181546001816001161561010002031660029004815260200191508054600181600116156101000203166002900480156101dc5780601f106101b1576101008083540402835291602001916101dc565b820191906000526020600020905b8154815290600101906020018083116101bf57829003601f168201915b5050935050505060405180910390f35b34610002576101fe60048050506105ac565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b338073ffffffffffffffffffffffffffffffffffffffff16600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1614151561028757610002565b6001600060005060008473ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548160ff021916908302179055507f078cba54125a07a375c22702c366fcb4d1029bafd27b1d6e93d813b1d103b6cb82604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390a15b5b5050565b600060005060205280600052604060002060009150909054906101000a900460ff1681565b3360001515600060005060008373ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009054906101000a900460ff161515141561038e57610002565b604060405190810160405280338152602001838152602001506002600050600085815260200190815260200160002060005060008201518160000160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908302179055506020820151816001016000509080519060200190828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061044657805160ff1916838001178555610477565b82800160010185558215610477579182015b82811115610476578251826000505591602001919060010190610458565b5b5090506104a29190610484565b8082111561049e5760008181506000905550600101610484565b5090565b50509050507f2ebfece40746549a3b7549b22060ca8d895e54ac0096edfb3aaee7db4acdc0ee833384604051808481526020018373ffffffffffffffffffffffffffffffffffffffff168152602001806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f16801561054d5780820380516001836020036101000a031916815260200191505b5094505050505060405180910390a15b5b505050565b60026000506020528060005260406000206000915090508060000160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff169080600101600050905082565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16815600000000000000000000000058f3d6e28fa4ac7e1a3f8a64d120ea10464f8634","gas":"0x47b760"}],"id":1475536685298343}
```

In the short term, you could test my theory by pointing MetaMask at a local `geth` node, and seeing if everything works like before. I think it should, which should isolate Parity as the current problem point.

**Comment by flyswatter** [comment]
I've made a few changes on our side to make our own errors more transparent (to be deployed soon).

I'm still debugging exactly why this request fails when sent to Parity, and that issue is being handled here:
https://github.com/ethcore/parity/issues/2448

In the short term, like I said in the last message, you can point MetaMask at geth and it works OK, we'll be actively trying to debug Parity's different requirements in the meanwhile.

**Comment by flyswatter** [comment]
We still haven't achieved full Parity compliance, but I'm adding my current work towards it here.

I've added param sanitization as a general subprovider module to provider-engine on this branch:
https://github.com/MetaMask/provider-engine/tree/Sanitizer

I've improved our handling of Parity's invalid param errors to MetaMask on this branch:
https://github.com/MetaMask/metamask-plugin/tree/ParityFix

That last patch makes it so MetaMask receives provider errors from the estimateGas call, and passes them directly back to the dapp without prompting the user to interact.  This allows you to more easily see the error we're getting from the backend when you make a call that triggers an error.

Still seeking the Parity pickiness, probably going to leave it overnight in hopes that they answer that issue.

**Comment by flyswatter** [comment]
Ok, I learned what Parity required differently, and have implemented the fixes in these PRs:

https://github.com/MetaMask/provider-engine/pull/88
https://github.com/MetaMask/metamask-plugin/pull/692

Note that provider-engine's version should be bumped in the plugin after merging.  MetaMask's fix should be complete after those merges.

There was one other component to this bug, and it's that the hex argument that was submitted in the example code needed to be encased in strings.

ie:
```
- var a = 0x58f3d6E28Fa4ac7e1A3f8a64d120ea10464f8634;
+ var a = '0x58f3d6E28Fa4ac7e1A3f8a64d120ea10464f8634';
```

**Comment by flyswatter** [comment]
Also, this could have been fixed user-side by hex-prefixing the data field.

The Parity team seems to think a hard failure is the best thing to do here. I think "trying to understand the intended meaning" is better behavior, and since we can automatically circumvent this problem in the future, that's what I've done.

**Comment by flyswatter** [comment]
Submitted a UI-side fix [here](https://github.com/stuffyvater/M-rskG2/pull/1).

**Comment by stuffyvater** [comment]
Thank you for the update Dan, I'll run this through with Søren later today who is at class atm and will get back to you! 👍

**Comment by stuffyvater** [comment]
Success! We're almost back again, thank you so much for your help Dan! I'm having some problems with IPFS now but I don't think that i MetaMask related.  Hope to share another Dapp that runs on MM with you guys soon :)

**Comment by flyswatter** [comment]
That's great to hear, good luck with the rest of your project!
