### ISSUE TITLE
Metamask becomes slower and slower over time

### ISSUE THREAD

**Issue by chevdor** [MetaMask/metamask-plugin#789]
After a few hours of intensive usage (DAPP dev that requites often testing transactions), Metamask  (the confirmation dialog) becomes slower and slower: slower to show up and slower to react once the confirm button is clicked.

Disabling the extension and enabling it again fixes the issue.

**Comment by wighawag** [comment]
I can confirm that. After few interaction with metamask  (I did not need to wait hours, just few transaction or interactions with the ui like switching account) it gets very slow. On my PC it can take up to 5 second for the plugin popup to who up, 5 more second to have it responsive to click, then 5 second for each new screen. This becomes almost unusable.

It migth explain : https://github.com/MetaMask/metamask-plugin/issues/863

**Comment by wighawag** [comment]
Any update on this ?

For our dapp, this affect players a lot after several plays and they cannot continue playing.

Could there be a workaround in the meantime (maybe a button to reload metamask or auto reload upon having dealt x transactions ) ?

Note that the issue seems to disappear upon disabling and enabling the extensions as @chevdor mentions

**Comment by flyswatter** [comment]
We've patched one major memory leak, and suspect there are more in our cache subprovider. One workaround may be to temporarily remove our cache layer.

We're probably going to have to do that next week though, we've taken this week off for the holidays.

It will be helpful to see if you have the same results with no caching.

- Dan

**Comment by wighawag** [comment]
Thanks Dan.
An option to enable/disable caching would be great.
Have great holidays!

**Comment by chevdor** [comment]
yep, if caching can be the issue, I like the proposal from @wighawag to have a checkbox to turn it off. That would make testing rather simple until the issue is fixed.

**Comment by wighawag** [comment]
Another option if it is possible for metamask to detect its own slow down, would be give a message to the user (instead of showing the transaction UI) .
This coud also then return a specific error to the dapp on transaction attempts

**Comment by kumavis** [comment]
@wighawag when you show the slowdown message in etherspace, how are you detecting a slow down?

**Comment by wighawag** [comment]
@kumavis We do not really detect it directly. When a player click start we do a first eth_call and if this take longer than usual (currently set to be 1.5 second) we show the message mentioning metamask slow down.

This is not accuratly detecting the metamask slow down though but we thought better have false positive so player get aware of potential slow down.

**Comment by kumavis** [comment]
its not uncommon for infura requests to take >2 sec when they are under stress, so I would remove that detection. Its unrelated to "MetaMask Slowdown". I don't find the false positive as helpful, if there is a real slow down the user will notice it because it is slow.

**Comment by wighawag** [comment]
@kumavis noted. The main problem is that when the slow down seems exponential. So a player could have a manageable slow down on start and a big slow down at submit time. This can be very frustarting for a player we manage to get into the highscore.

**Comment by chevdor** [comment]
Same experience as @wighawag

**Comment by kumavis** [comment]
Ok we will prioritize this

**Comment by chevdor** [comment]
That would be awesome, this is kinda the last blocker I have on my list
regarding Metamask atm.
Thank you @kumavis
Count me in once some testing is required

**Comment by kumavis** [comment]
We identified and fixed some significant memory leaks. Should improve the situation dramatically.

**Comment by wighawag** [comment]
Did not try for long but this seems indeed a lot better.  I ll try to test it more soon

**Comment by kumavis** [comment]
@wighawag haha unless you are building from the dev branch we actually haven't deployed anything new yet

**Comment by wighawag** [comment]
ok, I ll test more so that I can compare to Monday :)

**Comment by kumavis** [comment]
@wighawag the fix has been deployed. I'm closing for now but if you encounter this again, please let us know

**Comment by jmcgihon** [comment]
I get this problem still on Windows 7 Chrome 59.0.3071.115, Metamask 3.7.8

**Comment by fvictorio** [comment]
This is still happens to me. Using Ubuntu 17.04, Chrome 60.0.3112.113, MetaMask 3.13.2. A co-worker of mine has the same issue.

**Comment by BigMurry** [comment]
Same for me. Metamask takes very long time (maybe a few minutes) to show up pop ups for making transaction.
**MacOS Hign Sirra 10.13.2; Chrome  63.0.3239.132, Metamask 3.13.2**

**Comment by philipp65** [comment]
Can confirm. About 10 Minutes waiting time for the transaction popup. If a make multiple transactions they all come in a batch afterwards. Each new transaction takes about a minute longer. Will try it on Windows tonight.
MacOS High Sierra 10.13.2; Chrome 63.0.3239.132; Metamask 3.13.2

**Comment by mediumjack1** [comment]
has this issue been resolved? do I need to disable metamask in order for it to work properly? Will my ETH be safe doing this?

**Comment by mediumjack1** [comment]
The issue was fixed by resetting mettamask in settings. some unfinished transactions were slowing down the process

**Comment by gititGoro** [comment]
I'm still experiencing this issue. I find myself having to disable/enable the extension several times in chrome. The dapp I'm developing is becoming unusable after very metamask confirmation dialog popups. Ubuntu 18.04. Metamask 7.0.1

**Comment by danfinlay** [comment]
> The dapp I'm developing is becoming unusable after very few metamask confirmation dialog popups. Ubuntu 18.04. Metamask 7.0.1

Are you able to share the dapp you are building with us, so we could look into root causes?

**Comment by gititGoro** [comment]
> > The dapp I'm developing is becoming unusable after very few metamask confirmation dialog popups. Ubuntu 18.04. Metamask 7.0.1
> 
> Are you able to share the dapp you are building with us, so we could look into root causes?

Just to confirm, I've finally tested the dapp on Hanache, kovan and mainnet and the slow down only occurs for Ganache. So perhaps this is a Ganache issue rather than a Metamask issue. 
I'd encourage anyone having similar issues to deploy to a test net to confirm that it's not just ganache.
