### ISSUE TITLE
Transaction popup does not disapear after confirming transaction

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-plugin#951]
Currently as opposed to previous version the transaction popup does not disapear after confirming or rejecting. Instead the account info is displayed.

This is annoying from the user point of view, as she/he needs to deal with that popup (by closing it or moving it) to see the dapp under it. Since the tx originate from the dapp, the control should be given back to the dapp as soon as the user confirm or reject the tx.

Is there any reason why this changed in recent version ?

**Comment by flyswatter** [comment]
This was no deliberate change, @Zanibas is attempting to reproduce now (I was using our production build earlier and didn't experience this).

Any tips on reproduction?  What dapp are you using?

**Comment by Zanibas** [comment]
I just tried a reproduction on our test faucet--not able to reproduce the behavior. Is this a network-specific behavior perhaps? Have not tested on main-net.

**Comment by wighawag** [comment]
This is not reproducible on my machine but this still happen on the machine we noticed it first. We use testnet and our own dapp.

**Comment by flyswatter** [comment]
Without being able to reproduce this ourselves, it is up to the person experiencing it to give us any logs that might hint at what's wrong:

https://github.com/MetaMask/faq/blob/master/LOGS.md

- Dan

**Comment by flyswatter** [comment]
Does this still happen on that original machine, @wighawag?

**Comment by wighawag** [comment]
It still does. We will try to get better info such as logs at a later time

**Comment by flyswatter** [comment]
I finally found this, it seemed to be happening specifically on the `eth_sign` screen, and if that's the same bug you had, I've fixed it in #1149.

**Comment by wighawag** [comment]
For us it was happening on the eth_sendTransaction call (we do not use eth_sign)
I ll reopen it if the issue still happen, thanks

**Comment by wighawag** [comment]
The problem persist and we had at least one player reporting same behavior
